name: hsarchiamaccesskeyrotation-SAM-pipeline

on:
  push:
    branches:
      - 'master'
      - 'feature**'
    paths:
      - 'hsarch-iam-accesskey-rotation/**'
  workflow_dispatch:
    inputs:
      isTrigger:
        type: boolean
        description: 'Trigger the workflow'
        default: false

env:
  # Default Environment Variables
  SAM_TEMPLATE: template.yaml
  PIPELINE_EXECUTION_ROLE: arn:aws:iam::257676781382:role/hsarch-build-infra
  CLOUDFORMATION_EXECUTION_ROLE: arn:aws:iam::257676781382:role/hsarch-build-infra

  # OHIO Environment Variables
  OHIO_STACK_NAME: hsarch-iam-accesskey-rotation-us-east-2
  OHIO_IMAGE_REPOSITORY: 257676781382.dkr.ecr.us-east-2.amazonaws.com/hsarch-iam-accesskey-rotation
  OHIO_REGION: us-east-2
  OHIO_ARTIFACTS_BUCKET: hsarch-artifactory-257676781382-us-east-2
  
  # N_VIRGINIA Environment Variables
  N_VIRGINIA_STACK_NAME: hsarch-iam-accesskey-rotation-us-east-1
  N_VIRGINIA_IMAGE_REPOSITORY: 257676781382.dkr.ecr.us-east-1.amazonaws.com/hsarch-iam-accesskey-rotation
  N_VIRGINIA_REGION: us-east-1
  N_VIRGINIA_ARTIFACTS_BUCKET: hsarch-artifactory-257676781382-us-east-1


permissions:
  id-token: write
  contents: read
jobs:

  build-and-test-feature:
    if: startsWith(github.ref, 'refs/heads/feature')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - run: sam build --debug
        working-directory: ./hsarch-iam-accesskey-rotation

  build-deploy-us-east-1:
    if: startsWith(github.repository, 'SearsHomeServices/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Assume the pipeline user role
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: ${{ env.N_VIRGINIA_REGION }}
          role-to-assume: ${{ env.PIPELINE_EXECUTION_ROLE }}
          role-session-name: deployment
          role-duration-seconds: 3600
          role-skip-session-tagging: true
          
      - name: Build resources
        run: sam build --debug
        working-directory: ./hsarch-iam-accesskey-rotation
        
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: Deploy to us-east-1
        run: sam deploy --stack-name ${N_VIRGINIA_STACK_NAME} --capabilities CAPABILITY_NAMED_IAM --region ${N_VIRGINIA_REGION} --no-fail-on-empty-changeset --image-repositories hsarchiamaccesskeyrotation=257676781382.dkr.ecr.us-east-1.amazonaws.com/hsarch-iam-accesskey-rotation --parameter-overrides "SecurityGroupIds=sg-0f9e4dfc04ceba8d6" "Subnets=subnet-0419ee49cb88df4bb,subnet-017ad4c8890a1175e,subnet-0b3ad7f6d3e393ea8" 
        working-directory: ./hsarch-iam-accesskey-rotation
    
  build-deploy-us-east-2:
    if: startsWith(github.repository, 'SearsHomeServices/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Assume the pipeline user role
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: ${{ env.OHIO_REGION }}
          role-to-assume: ${{ env.PIPELINE_EXECUTION_ROLE }}
          role-session-name: deployment
          role-duration-seconds: 3600
          role-skip-session-tagging: true
          
      - name: Build resources
        run: sam build --debug
        working-directory: ./hsarch-iam-accesskey-rotation
        
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: Deploy to us-east-2
        run: sam deploy --stack-name ${OHIO_STACK_NAME} --capabilities CAPABILITY_NAMED_IAM --region ${OHIO_REGION} --no-fail-on-empty-changeset --image-repositories hsarchiamaccesskeyrotation=257676781382.dkr.ecr.us-east-2.amazonaws.com/hsarch-iam-accesskey-rotation --parameter-overrides "SecurityGroupIds=sg-0c37a80d7ad4786b4" "Subnets=subnet-0942d4e5e58f733e2,subnet-012344d2e071d6770,subnet-0f080e257d72e48d4" 
        working-directory: ./hsarch-iam-accesskey-rotation
